name: dev_play_tictactuple
description: "Dev Play: Tic Tac Tuple"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'
  flutter: '3.22.0-0.3.pre'

dependencies:
  base_services:
    path: packages/base_services
  collection: ^1.18.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  rxdart: ^0.27.7

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/images/logo_tictactoe_1024.png"
  image_path_android: "assets/images/logo_tictactoe_1024.png"
  # adaptive_icon_background: "assets/images/kdrecall_icon_1024_back.png"
  # adaptive_icon_foreground: "assets/images/kdrecall_icon_1024_h_fore.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand-Regular.ttf
