name: base_services
description: Services relevant at the base app level
  (can be used as-is/out-of-the-box by other apps).

version: 0.1.0+1

publish_to: none

environment:
  sdk: '>=3.4.0-247.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.0.17

dev_dependencies:
  very_good_analysis: ^5.1.0
