name: build_release_tictactuple

on:
  push:
    branches: [ "build_release_tictactuple" ]
  pull_request:
    branches: [ "build_release_tictactuple" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./tic-tac-tuple

    steps:
      # https://github.com/marketplace/actions/setup-java-jdk#basic-configuration
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # https://github.com/Homebrew/brew/actions/runs/9770285377/workflow
      # https://8thlight.com/insights/how-to-set-up-github-actions
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install YQ and output version
        id: get_flutter_version
        # https://github.com/subosito/flutter-action/issues/282
        # https://github.com/subosito/flutter-action/discussions/293
        # https://github.com/subosito/flutter-action/blob/b6150a9d644588978ac48783d01e7dbde7031cfa/README.md
        run: |
          brew install yq
          echo "result=$(yq '.environment.flutter' pubspec.yaml)" >> $GITHUB_OUTPUT
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          # cache: 'gradle'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: beta
          # flutter-version: 3.22.0
          flutter-version: ${{ steps.get_flutter_version.outputs.result }}
          # flutter-version-file: pubspec.yaml
          # flutter-version-file: pubspec.yaml | environment: flutter: 3.22.0
          # flutter-version-file: ${{ steps.get_flutter_version.outputs.result }}
          cache: true

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      # - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: flutter pub get
      - name: Verify formatting
        run: dart format --output=none --line-length 100 --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze
      - name: Run tests
        run: flutter test
      - name: Start Web Release Build
        run: flutter build web --release
      - name: Upload Web Build Files
        uses: actions/upload-artifact@v4
        with:
          name: web-release
          path: ./tic-tac-tuple
      - name: List Files
        run: ls -R

  deploy:
    name: Deploy Web Build
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Web Release
      uses: actions/download-artifact@v4
      with:
        name: web-release
        path: ./tic-tac-tuple

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # publish_dir: ./
        publish_dir: ./tic-tac-tuple
